running
setUp
	usuario1:= UsuarioCuOOra newUsuarioNombreUsuario: 'Matias' Contraseña: 'Miguel'.
	usuario2:= UsuarioCuOOra newUsuarioNombreUsuario: 'Eve' Contraseña: 'Miguel'.
	topico:= Topico newTopicoNombre: 'Terror' Descripcion: 'Da Miedo'.
	topico2:= Topico newTopicoNombre: 'Amor' Descripcion: 'Da Miedo'.
	topico3:= Topico newTopicoNombre: 'Suspenso' Descripcion: 'Da Miedo'.
	topico4:= Topico newTopicoNombre: 'Investigacion' Descripcion: 'Da Miedo'.