rendering
style 
	^ '#agregarPreg{
	font: 15pt Arial;
	color: black;
        font-weight: bold;
text-decoration: none;

}

#userStyle{
	font: 12pt Arial;
	color: black;
        font-weight: bold;
text-decoration: none;

}

#tituloPregunta{
	font: 14pt Arial;
	color: black;
text-decoration: none;
font-style:italic;

}
#agregarRespuesta{

  text-align: right;
	font: 18pt Arial;
	color: black;
text-decoration: none;
        font-weight: bold;


}

#botones{
text-decoration: none;
    padding: 10px;
    font-weight: 600;
    font-size: 20px;
    color: #ffffff;
    background-color: #1883ba;
    border-radius: 4px;
   
}

'